= Fastsetup

image:Documents/svg/offical.svg[dahan]
image:Documents/svg/test.svg[test]
image:Documents/svg/license.svg[dahan]
image:Documents/svg/build.svg[build]

Java 后端微服务、单体服务快速开发框架。

== 开发文档

项目规范文档列表（开发前请阅读）：

- link:Documents/codestyle.adoc[代码规范文档]
- link:Documents/commit-style.adoc[提交规范文档]

== 构建环境要求

此项目使用 Maven toolchains 进行构建操作，JDK要求21及以上，JDK版本最低要求 21。

JDK21 是 OpenJDK 的一个 LTS 版本，通常我们可以选择不同的发行版进行开发或部署，常用 JDK 发行版：

* link:https://openjdk.org/projects/jdk/21/[OpenJDK]
* link:https://www.oracle.com/java/technologies/javase/jdk21-archive-downloads.html[Oracle OpenJDK]
* link:https://aws.amazon.com/cn/corretto/?filtered-posts.sort-by=item.additionalFields.createdDate&filtered-posts.sort-order=desc[Aws Corretto]
* link:https://github.com/dragonwell-project/dragonwell21[Alibaba Dragonwell]

=== 构建

构建项目前请**务必**按照 link:install.txt[install.txt] 中描述的模块按顺序安装到把本地。否则在执行 `clean` 或 `package` 等命令的时候会抛出找不到依赖版本的异常。

本项目使用 Maven 进行构建，你需要在你本地的环境变量中添加 Maven 的 `/bin` 目录地址，并指定 Maven Home

    MAVEN_HOME=<your maven home>

相信如何添加环境变量对于任何一个程序员来说都是最基础的操作这里就不再过多的赘述。

在终端上执行 `mvn package` 对项目进行构建，通常来说构建出来的 `jar` 包的大小一般在 100MB 以上，如果你构建出来的包没有这么大，那么你需要检查一下是否执行了一次正确构建。