#!/bin/bash

# ************************************************************************
#
# Copyright (C) 2020 RedGogh All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# ************************************************************************

# Author     RedGogh
# CreateTime 2023/06/28

merge() {
  echored "+ git merge origin $@"
  git merge origin "$@"
  exit
}

if [ -z "$1" ]; then
  branches=$(xbranch --format="%(refname:lstrip=2)")
  IFS=$'\n' read -rd '' -a array <<< "$branches"

  echo "All branch in local (exclude for remote branch):"
  count=1
  for element in "${array[@]}"; do
    echo "    [$count] - $element"
    ((count++))
  done

  read -p "Switch branch of number: " number
  branch="${array[((number - 1))]}"

  echopurple "+ xmerge $branch"
  echo "Merging to branch '$branch' for you"
  merge $branch
fi

merge "$@"
