#!/bin/bash

# ************************************************************************
#
# Copyright (C) 2020 RedGogh All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# ************************************************************************

# Author     RedGogh
# CreateTime 2023/06/28

echored "+ git status --porcelain"
log=$(git status --porcelain)

while IFS= read -r line; do
  records=($line)

  stat=${records[0]}
  desc=${records[1]}

  status="$stat"
  if [ ${#status} -eq 1 ]; then
    status=" $status"
  fi

  eout="$status       $desc"

  if [ "$stat" = "RM" ] || [ "$stat" = "D" ]; then
    echogreen "$eout" # 删除输出红色
  elif [ "$stat" = "A" ] || [ "$stat" = "AM" ]; then
    echogreen "$eout" # 新增输出绿色
  else
    echo "$eout"
  fi

done <<< "$log"
